### PR TITLE
Sync with authoritative repository

### PR DESCRIPTION
**Pull request by uturuncoglu**
## Description:
This PR aims to sync the ocean modeling fork of ufo-weather-model with the authoritative repository.

### Sub component Pull Requests:
There is no update in sub-module side in terms of UFS Coastal specific model components.

## Changes
None. All tests found under `rt_coastal.conf` runs and pass the baseline except FVCOM due to known issue https://github.com/oceanmodeling/FVCOM/issues/2.

### Input data Changes:
None

### Library Changes/Upgrades:
None. The sync updates spack-stack to version 1.6.0 which uses ESMF 8.6.0.

### CODE REVIEW

**Comment by uturuncoglu** [comment]
@janahaddad @pvelissariou1 This PR will sync our fork. I am running RTs at this point to be sure everything is fine. I'll update you soon. BTW, this PR will also change the baseline date. I fixed on Hercules but it needs to be fixed on also other testing platforms such as Orion, Frontera etc. Anyway, I'll put here more information about it once I tests are finished.

**Comment by uturuncoglu** [comment]
with this update atm2ww3 requires running ww3_grid to update mod_def.ww3 otherwise it is failing. I'll try to regenerate it. @janahaddad I am not sure when we push the inputs to S3 bucket but at least we need to be consistent with the input files across the testing platforms (Orion, Frontera & Hera). At this point I am working on Hercules and once it is done we need to sync the input directory with other platforms.

**Comment by uturuncoglu** [comment]
Once I created file with `ww3_grid` the test passed. The input directory on Hercules in `/work2/noaa/nems/tufuk/RT/NEMSfv3gfs/input-data-20240501`. I am testing one more last configuration with GNU.

**Comment by uturuncoglu** [comment]
Okay. GNU is also working fine. I think this is ready to merge. There is no any baseline change but the input directory (Hercules, /work2/noaa/nems/tufuk/RT/NEMSfv3gfs/input-data-20240501 - not that this directory also has some input directories for other configurations outside of UFS Coastal) needs to be sync across platforms and baseline directory needs to be renamed or copied like `develop-20240614`.

**Comment by uturuncoglu** [comment]
@pvelissariou1 If you don't have time to review just let me know. Then, I could merge it without approval. Actually, there is nothing specific to coastal modeling and the changes that I did. It is just a sync but it would be nice to start reviewing/approving practice.

**Review by pvelissariou1 — APPROVED** [review]
It seems everything is ok. Compilation/run test cases maybe needed.

**Comment by pvelissariou1** [comment]
@uturuncoglu Please sync SCHISM as well (use the commit I suggested). After this, we will discuss/review my PR.

**Comment by uturuncoglu** [comment]
@pvelissariou1 Let me merge this one first. Then, I'll work on syncing SCHSIM and ROMS too. ROMS develop was creating an issue but I need to check again.

**Comment by uturuncoglu** [comment]
@pvelissariou1 BTW, I have already test the RTs in rt_coastal.conf and they are all fine.

**Comment by pvelissariou1** [comment]
@uturuncoglu Great, thanks. After you finish your tasks please do SCHISM & ROMS. I have tested this SCHISM commit extensively and everything looks fine.

**Comment by uturuncoglu** [comment]
@pvelissariou1 Okay. Let me update SCHISM repositories first. If tests runs without any issue, I'll do direct push to speed up the process.

**Pull request merged**
